alias gl="git pull --rebase"
alias gp="git push"
alias gst="git status"
alias grv="git remote --verbose"
alias gaa="git add --all"
alias ga="git add"
alias gc="git commit"
alias gca="git commit --amend"
alias glo="git log --oneline"
alias gb="git branch"
alias gba="git branch --all"
alias gd="git diff"
alias gds="git diff --staged"

alias lg="lazygit"
