alias gl="git pull --rebase"
alias gp="git push"
alias gst="git status"
alias grv="git remote --verbose"
alias gaa="git add --all"
alias ga="git add"
alias gc="git commit"
alias glo="git log --oneline"
